name: 'Remind Collaborators to Review Items'
description: 'Post Reminders to Github Issues using the {gh} package and REST API.'
author: 'Jonathan D. Trattner'
inputs:
  github_repo:
    description: 'Github Repo where reminders should be issued'
    default: '$ {{ github.repository }}'
  github_pat: 
    description: 'Github token for performing actions on behalf of a user'
    default: '$ {{ secrets.GITHUB_TOKEN }}'
    
runs:
  main: 'R/remind_collaborator.R'