on: 
  schedule:
    - cron: "0 */11 * * 1,3,5"
  
name: Reminders

jobs:
  Testing-gh:
    runs-on: macOS-latest
    env:
      MY_GITHUB_REPO: ${{ github.repository }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages("remotes")
          devtools::install_github("jdtrat/simplegit")
        shell: Rscript {0}
      - name: Remind Mason
        run: |
          source("reminders/R/remind_collaborator.R")
        shell: Rscript {0}