on: 
  workflow_dispatch:
  
name: Testing-gh

jobs:
  Testing-gh:
    runs-on: macOS-latest
    env:
      MY_GITHUB_REPO: ${{ github.repository }}
      GITHUB_PAT: ${{ secrets.GIT_PAT_PLUS }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages("gh")
        shell: Rscript {0}
      - name: Add an Issue
        run: |
          source("ds4psych/R/create_issue.R")
        shell: Rscript {0}
      - name: Inviting
        run: |
          source("ds4psych/R/invite_mason.R")
        shell: Rscript {0}
